AllCops:
  SuggestExtensions: false
  NewCops: enable
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Metrics/AbcSize:
  Enabled: false 

